// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENax7MhOQ4jU8LhNObEe7h5zcuI6RTIQ',
    appId: '1:1073793909493:web:2cff68e227cabd03afbbbc',
    messagingSenderId: '1073793909493',
    projectId: 'flutter-kafe-exam',
    authDomain: 'flutter-kafe-exam.firebaseapp.com',
    storageBucket: 'flutter-kafe-exam.firebasestorage.app',
    measurementId: 'G-4C77FG2Q2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWkTrXoqmXnR0NVNfM75oA-Uq5UUD6QQ',
    appId: '1:1073793909493:android:78c1a4c38ce2f80cafbbbc',
    messagingSenderId: '1073793909493',
    projectId: 'flutter-kafe-exam',
    storageBucket: 'flutter-kafe-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4NbbtpSkUGWHW7E-Qc0z7LXnqxENxYU',
    appId: '1:1073793909493:ios:948a6618bda2a006afbbbc',
    messagingSenderId: '1073793909493',
    projectId: 'flutter-kafe-exam',
    storageBucket: 'flutter-kafe-exam.firebasestorage.app',
    iosBundleId: 'com.example.kafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4NbbtpSkUGWHW7E-Qc0z7LXnqxENxYU',
    appId: '1:1073793909493:ios:948a6618bda2a006afbbbc',
    messagingSenderId: '1073793909493',
    projectId: 'flutter-kafe-exam',
    storageBucket: 'flutter-kafe-exam.firebasestorage.app',
    iosBundleId: 'com.example.kafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENax7MhOQ4jU8LhNObEe7h5zcuI6RTIQ',
    appId: '1:1073793909493:web:79c80ea57319d542afbbbc',
    messagingSenderId: '1073793909493',
    projectId: 'flutter-kafe-exam',
    authDomain: 'flutter-kafe-exam.firebaseapp.com',
    storageBucket: 'flutter-kafe-exam.firebasestorage.app',
    measurementId: 'G-F73CJBEGTN',
  );
}
